application:
  title: FlockData SearchWriter

eureka:
  client:
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: ${org.fd.discovery.url:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true

#    enabled: false

spring:
  application:
    name: fd-search
  profiles:
    active: fd-no-auth
    include: fd-server
#    Run with the "discovery" profile active to connect
#  cloud:
#    discovery:
#      enabled: false
  messages:
    encoding: UTF-8
  rabbitmq:
    password: guest
    username: guest
    host: localhost
    port: 5672
    virtual-host: /

server:
  port: 8081

es:
  clustername: es_flockdata
  # this clients ports
  http:
    port: 9200
  tcp:
    port: 9300

  path:
    home: ./data/
    data: ${es.path.home}/fd/es


  # , serparated list of hosts to connect to if transportOnly == true
#  nodes: localhost:9300


org.fd:
  engine:
    api: http://localhost:8080
    messaging:
      prefetchCount: 3
      concurrentConsumers: 2
    executor:
      poolSize: 4
      capacity: 4
  search:
    es:
      mappings: ./
      #Is the node going to be a client node which means it will hold no data ?
      # True for production/cluster
      # False for dev/demo (default)
      transportOnly: false

      # Look outside of this jvm for an ES host
      # True for dev/transportOnly = false (default)
      # False for production/cluster/remote es client
      local: true

    system:
      api: api
    messaging:
      concurrentConsumers: 2
      prefetchCount: 3
    executor:
      poolSize: 4
      capacity: 10



