package com.auditbucket.demo.services;

import com.auditbucket.demo.domain.Account;
import com.auditbucket.demo.repository.AccountRepository;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

@RunWith(SpringJUnit4ClassRunner.class)
@Transactional(propagation = Propagation.NOT_SUPPORTED)
@ContextConfiguration(locations = {"classpath:applicationContext-test.xml"})
public class AccountServiceTest {

    public static Logger logger = LoggerFactory.getLogger(AccountServiceTest.class);
    @Autowired
    private AccountService accountService;
    @Autowired
    private AccountRepository accountRepository;

    @Ignore
    @Test
    public void testSaveAccount() throws IllegalAccessException {
        Account account = new Account();
        account.setNrCompte("numAccount");
        account.setIban("iban");
        account.setRib("rib");
        account.setCodeAgence("codeagence");
        accountService.saveAccount(account);

        Account accountDb = accountRepository.findByNrCompte("numAccount");
        Assert.assertNotNull(accountDb);
        Assert.assertEquals(accountDb.getNrCompte(), "numAccount");
        Assert.assertEquals(accountDb.getIban(), "iban");
        Assert.assertEquals(accountDb.getRib(), "rib");
        Assert.assertEquals(accountDb.getCodeAgence(), "codeagence");
        Assert.assertNotNull(accountDb.getAuditKey());
        logger.info("Audit Key Generated By Ab Engine is : {}", accountDb.getAuditKey());
    }
}
