#!/bin/bash
function findBaseDirAndCdThere {
    CDPATH=""
    SCRIPT="$0"

    # SCRIPT may be an arbitrarily deep series of symlinks. Loop until we have the concrete path.
    while [ -h "$SCRIPT" ] ; do
      ls=`ls -ld "$SCRIPT"`
      # Drop everything prior to ->
      link=`expr "$ls" : '.*-> \(.*\)$'`
      if expr "$link" : '/.*' > /dev/null; then
        SCRIPT="$link"
      else
        SCRIPT=`dirname "$SCRIPT"`/"$link"
      fi
    done

  AB_HOME=`cd $( dirname "$SCRIPT" )/.. && dirs -l +0`
  AB_CONFIG=$AB_HOME/conf
  AB_APP=$AB_HOME/app

  cd "$AB_HOME"
}
if [ -x "$JAVA_HOME/bin/java" ]; then
    JAVA="$JAVA_HOME/bin/java"
else
    JAVA=$(which java)
fi

if [ ! -x "$JAVA" ]; then
    echo "Could not find any executable java binary. Please install java in your PATH or set JAVA_HOME"
    exit 1
fi
findBaseDirAndCdThere

## Countries
## match (c:Country) return c;
$JAVA -classpath $AB_APP/ab-client.jar com.auditbucket.client.Importer -c ${AB_CONFIG} "/countries.json, /JsonTags.json"

