# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|

  config.vm.box = "lucid32"
  config.vm.box_url = "http://files.vagrantup.com/lucid32.box"

  config.vm.forward_port 80, 8080
  config.vm.forward_port 55672, 55672
  config.vm.forward_port 15672, 15672
  config.vm.forward_port 5672, 5672

  config.vm.provision :chef_solo do |chef|
	chef.cookbooks_path = "../cookbooks"

	chef.add_recipe "emacs"
	chef.add_recipe "apt"
	chef.add_recipe "python"
	chef.add_recipe "erlang"
  chef.add_recipe "rabbitmq"

	chef.json = {
	    }

  end
end
