/*
 *  Copyright 2012-2016 the original author or authors.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.flockdata.test.unit.client;

import org.junit.Test;

/**
 * @author mholdsworth
 * @since 22/09/2014
 */
public class TestBigXmlToJson {
    @Test
    public void blah() throws Exception {
//        JSONObject json = XML.toJSONObject(getXml());
//        ObjectMapper mapper = new ObjectMapper();
//
//        Map<String,Object> map = new HashMap<>();
//        JSONObject message = json.getJSONObject("MESSAGE");
//        JSONObject header = message.getJSONObject("HEADER");
//        JSONObject details = message.getJSONObject("MORTGAGEINS_XCM");
//        JSONObject parties = details.getJSONObject("PARTIES");
//        JSONObject assets = details.getJSONObject("ASSETS");
//
//        JSONArray assetArray = assets.getJSONArray("ASSET");
//        int x = assetArray.length();
//        int i = 0;
//        ArrayList arrayList = new ArrayList();
//        while ( i < x) {
//            JSONObject o = assetArray.getJSONObject(0);
//            i ++;
//        }
//        map.put("ASSETS" , null);
//        map.put("PARTIES", parties.getJSONArray("PARTY"));

//        String parsedJson = mapper.writeValueAsString(map);
        //      System.out.println(parsedJson);

        //assertEquals ("Walnes", jsonObject.getJSONObject("person").get("lastname"));
    }

    public String getXml() {
        return
            "<MESSAGE>\n" +
                "\t<HEADER>\n" +
                "\t\t<HEADER_DETAIL>\n" +
                "\t\t\t<MessageIdentifier>52C55B33-B048-8BBB-9980-3E1886C6AB9B</MessageIdentifier>\n" +
                "\t\t\t<MessageTimestamp>2014-04-02T07:25:47Z</MessageTimestamp>\n" +
                "\t\t\t<RecordCount>1</RecordCount>\n" +
                "\t\t\t<TransactionIdentifier>52C55B33-B048-8BBB-9980-3E1886C6AB9B</TransactionIdentifier>\n" +
                "\t\t</HEADER_DETAIL>\n" +
                "\t\t<SOURCE>\n" +
                "\t\t\t<ApplicationName>Portal</ApplicationName>\n" +
                "\t\t</SOURCE>\n" +
                "\t</HEADER>\n" +
                "\t<MORTGAGEINS_XCM>\n" +
                "\t\t<ASSETS>\n" +
                "\t\t\t<ASSET>\n" +
                "\t\t\t\t<ASSET_DETAIL>\n" +
                "\t\t\t\t\t<AssetAccountIdentifier>12345</AssetAccountIdentifier>\n" +
                "\t\t\t\t\t<AssetCashOrMarketValueAmount>23000</AssetCashOrMarketValueAmount>\n" +
                "\t\t\t\t\t<AssetType>MoneyMarketFund</AssetType>\n" +
                "\t\t\t\t\t<AssetDescription>AnyBankUSA</AssetDescription>\n" +
                "\t\t\t\t</ASSET_DETAIL>\n" +
                "\t\t\t\t<OWNED_PROPERTY>\n" +
                "\t\t\t\t\t<OWNED_PROPERTY_DETAIL>\n" +
                "\t\t\t\t\t\t<OwnedPropertyDispositionStatusType>RetainForPrimaryOrSecondaryResidence</OwnedPropertyDispositionStatusType>\n" +
                "\t\t\t\t\t\t<OwnedPropertyLienInstallmentAmount>1189</OwnedPropertyLienInstallmentAmount>\n" +
                "\t\t\t\t\t\t<OwnedPropertyLienUPBAmount>120000</OwnedPropertyLienUPBAmount>\n" +
                "\t\t\t\t\t\t<OwnedPropertyMarketValueAmount>315</OwnedPropertyMarketValueAmount>\n" +
                "\t\t\t\t\t\t<OwnedPropertyMaintenanceExpenseAmount>550</OwnedPropertyMaintenanceExpenseAmount>\n" +
                "\t\t\t\t\t\t<OwnedPropertyRentalIncomeGrossAmount>650</OwnedPropertyRentalIncomeGrossAmount>\n" +
                "\t\t\t\t\t\t<OwnedPropertyRentalIncomeNetAmount>315</OwnedPropertyRentalIncomeNetAmount>\n" +
                "\t\t\t\t\t</OWNED_PROPERTY_DETAIL>\n" +
                "\t\t\t\t\t<PROPERTY>\n" +
                "\t\t\t\t\t\t<ADDRESS>\n" +
                "\t\t\t\t\t\t\t<AddressLineText>7453 Madison St</AddressLineText>\n" +
                "\t\t\t\t\t\t\t<AddressAdditionalLineText>test</AddressAdditionalLineText>\n" +
                "\t\t\t\t\t\t\t<CityName>Dearborn</CityName>\n" +
                "\t\t\t\t\t\t\t<PostalCode>48126</PostalCode>\n" +
                "\t\t\t\t\t\t\t<StateCode>MI</StateCode>\n" +
                "\t\t\t\t\t\t\t<CountyName>county test</CountyName>\n" +
                "\t\t\t\t\t\t</ADDRESS>\n" +
                "\t\t\t\t\t\t<PROPERTY_DETAIL/>\n" +
                "\t\t\t\t\t</PROPERTY>\n" +
                "\t\t\t\t</OWNED_PROPERTY>\n" +
                "\t\t\t</ASSET>\n" +
                "\t\t\t<ASSET>\n" +
                "\t\t\t\t<ASSET_DETAIL>\n" +
                "\t\t\t\t\t<AssetAccountIdentifier>999845</AssetAccountIdentifier>\n" +
                "\t\t\t\t\t<AssetCashOrMarketValueAmount>32000</AssetCashOrMarketValueAmount>\n" +
                "\t\t\t\t\t<AssetType>SavingsAccount</AssetType>\n" +
                "\t\t\t\t\t<AssetDescription>AnyBankUSA</AssetDescription>\n" +
                "\t\t\t\t</ASSET_DETAIL>\n" +
                "\t\t\t\t<OWNED_PROPERTY>\n" +
                "\t\t\t\t\t<OWNED_PROPERTY_DETAIL>\n" +
                "\t\t\t\t\t\t<OwnedPropertyDispositionStatusType>RetainForPrimaryOrSecondaryResidence</OwnedPropertyDispositionStatusType>\n" +
                "\t\t\t\t\t\t<OwnedPropertyLienInstallmentAmount>1189</OwnedPropertyLienInstallmentAmount>\n" +
                "\t\t\t\t\t\t<OwnedPropertyLienUPBAmount>120000</OwnedPropertyLienUPBAmount>\n" +
                "\t\t\t\t\t\t<OwnedPropertyMarketValueAmount>315</OwnedPropertyMarketValueAmount>\n" +
                "\t\t\t\t\t\t<OwnedPropertyRentalIncomeGrossAmount>650</OwnedPropertyRentalIncomeGrossAmount>\n" +
                "\t\t\t\t\t\t<OwnedPropertyRentalIncomeNetAmount>315</OwnedPropertyRentalIncomeNetAmount>\n" +
                "\t\t\t\t\t\t<OwnedPropertyMaintenanceExpenseAmount>315</OwnedPropertyMaintenanceExpenseAmount>\n" +
                "\t\t\t\t\t</OWNED_PROPERTY_DETAIL>\n" +
                "\t\t\t\t\t<PROPERTY>\n" +
                "\t\t\t\t\t\t<ADDRESS>\n" +
                "\t\t\t\t\t\t\t<AddressLineText>7452 Madison St</AddressLineText>\n" +
                "\t\t\t\t\t\t\t<AddressAdditionalLineText>test</AddressAdditionalLineText>\n" +
                "\t\t\t\t\t\t\t<CityName>Dearborn</CityName>\n" +
                "\t\t\t\t\t\t\t<PostalCode>48126</PostalCode>\n" +
                "\t\t\t\t\t\t\t<StateCode>MI</StateCode>\n" +
                "\t\t\t\t\t\t\t<CountyName>county test</CountyName>\n" +
                "\t\t\t\t\t\t</ADDRESS>\n" +
                "\t\t\t\t\t\t<PROPERTY_DETAIL/>\n" +
                "\t\t\t\t\t</PROPERTY>\n" +
                "\t\t\t\t</OWNED_PROPERTY>\n" +
                "\t\t\t</ASSET>\n" +
                "\t\t\t<ASSET>\n" +
                "\t\t\t\t<OWNED_PROPERTY>\n" +
                "\t\t\t\t\t<OWNED_PROPERTY_DETAIL>\n" +
                "\t\t\t\t\t\t<OwnedPropertyDispositionStatusType>RetainForPrimaryOrSecondaryResidence</OwnedPropertyDispositionStatusType>\n" +
                "\t\t\t\t\t\t<OwnedPropertyLienInstallmentAmount>1189</OwnedPropertyLienInstallmentAmount>\n" +
                "\t\t\t\t\t\t<OwnedPropertyLienUPBAmount>120000</OwnedPropertyLienUPBAmount>\n" +
                "\t\t\t\t\t\t<OwnedPropertyMarketValueAmount>315</OwnedPropertyMarketValueAmount>\n" +
                "\t\t\t\t\t\t<OwnedPropertyRentalIncomeGrossAmount>650</OwnedPropertyRentalIncomeGrossAmount>\n" +
                "\t\t\t\t\t\t<OwnedPropertyRentalIncomeNetAmount>315</OwnedPropertyRentalIncomeNetAmount>\n" +
                "\t\t\t\t\t\t<OwnedPropertyMaintenanceExpenseAmount>315</OwnedPropertyMaintenanceExpenseAmount>\n" +
                "\t\t\t\t\t</OWNED_PROPERTY_DETAIL>\n" +
                "\t\t\t\t\t<PROPERTY>\n" +
                "\t\t\t\t\t\t<ADDRESS>\n" +
                "\t\t\t\t\t\t\t<AddressLineText>7451 Madison St</AddressLineText>\n" +
                "\t\t\t\t\t\t\t<CityName>Dearborn</CityName>\n" +
                "\t\t\t\t\t\t\t<PostalCode>48126</PostalCode>\n" +
                "\t\t\t\t\t\t\t<StateCode>MI</StateCode>\n" +
                "\t\t\t\t\t\t\t<CountyName>county test</CountyName>\n" +
                "\t\t\t\t\t\t</ADDRESS>\n" +
                "\t\t\t\t\t\t<PROPERTY_DETAIL/>\n" +
                "\t\t\t\t\t</PROPERTY>\n" +
                "\t\t\t\t</OWNED_PROPERTY>\n" +
                "\t\t\t</ASSET>\n" +
                "\t\t</ASSETS>\n" +
                "\t\t<LIABILITIES>\n" +
                "\t\t\t<LIABILITY>\n" +
                "\t\t\t\t<LIABILITY_DETAIL>\n" +
                "\t\t\t\t\t<LiabilityPayoffStatusIndicator>false</LiabilityPayoffStatusIndicator>\n" +
                "\t\t\t\t\t<LiabilityDescription>American Express</LiabilityDescription>\n" +
                "\t\t\t\t\t<LiabilityMonthlyPaymentAmount>25.0</LiabilityMonthlyPaymentAmount>\n" +
                "\t\t\t\t\t<LiabilityRemainingTermMonthsCount>20</LiabilityRemainingTermMonthsCount>\n" +
                "\t\t\t\t\t<LiabilityUnpaidBalanceAmount>500.0</LiabilityUnpaidBalanceAmount>\n" +
                "\t\t\t\t\t<LiabilityType>Revolving</LiabilityType>\n" +
                "\t\t\t\t\t<LiabilityTypeOtherDescription>OtherRevolving</LiabilityTypeOtherDescription>\n" +
                "\t\t\t\t</LIABILITY_DETAIL>\n" +
                "\t\t\t</LIABILITY>\n" +
                "\t\t\t<LIABILITY>\n" +
                "\t\t\t\t<LIABILITY_DETAIL>\n" +
                "\t\t\t\t\t<LiabilityPayoffStatusIndicator>true</LiabilityPayoffStatusIndicator>\n" +
                "\t\t\t\t\t<LiabilityMonthlyPaymentAmount>500</LiabilityMonthlyPaymentAmount>\n" +
                "\t\t\t\t\t<LiabilityDescription>American Express</LiabilityDescription>\n" +
                "\t\t\t\t\t<LiabilityRemainingTermMonthsCount>20</LiabilityRemainingTermMonthsCount>\n" +
                "\t\t\t\t\t<LiabilityType>Installment</LiabilityType>\n" +
                "\t\t\t\t\t<LiabilityUnpaidBalanceAmount>1500.0</LiabilityUnpaidBalanceAmount>\n" +
                "\t\t\t\t\t<LiabilityTypeOtherDescription>OtherInstallment</LiabilityTypeOtherDescription>\n" +
                "\t\t\t\t</LIABILITY_DETAIL>\n" +
                "\t\t\t</LIABILITY>\n" +
                "\t\t\t<LIABILITY>\n" +
                "\t\t\t\t<LIABILITY_DETAIL>\n" +
                "\t\t\t\t\t<LiabilityDescription>American Express</LiabilityDescription>\n" +
                "\t\t\t\t\t<LiabilityMonthlyPaymentAmount>700</LiabilityMonthlyPaymentAmount>\n" +
                "\t\t\t\t\t<LiabilityPayoffStatusIndicator>false</LiabilityPayoffStatusIndicator>\n" +
                "\t\t\t\t\t<LiabilityRemainingTermMonthsCount>142</LiabilityRemainingTermMonthsCount>\n" +
                "\t\t\t\t\t<LiabilityType>MortgageLoan</LiabilityType>\n" +
                "\t\t\t\t</LIABILITY_DETAIL>\n" +
                "\t\t\t</LIABILITY>\n" +
                "\t\t</LIABILITIES>\n" +
                "\t\t<COLLATERALS>\n" +
                "\t\t\t<COLLATERAL>\n" +
                "\t\t\t\t<SUBJECT_PROPERTY>\n" +
                "\t\t\t\t\t<PROJECT>\n" +
                "\t\t\t\t\t\t<PROJECT_DETAIL>\n" +
                "\t\t\t\t\t\t\t<ProjectName>The Project</ProjectName>\n" +
                "\t\t\t\t\t\t\t<ProjectLegalStructureType>CommonInterestApartment</ProjectLegalStructureType>\n" +
                "\t\t\t\t\t\t</PROJECT_DETAIL>\n" +
                "\t\t\t\t\t</PROJECT>\n" +
                "\t\t\t\t\t<ADDRESS>\n" +
                "\t\t\t\t\t\t<AddressLineText>123 harmony st</AddressLineText>\n" +
                "\t\t\t\t\t\t<AddressAdditionalLineText>1100,test</AddressAdditionalLineText>\n" +
                "\t\t\t\t\t\t<CityName>peace</CityName>\n" +
                "\t\t\t\t\t\t<PostalCode>12321</PostalCode>\n" +
                "\t\t\t\t\t\t<CountyName>County</CountyName>\n" +
                "\t\t\t\t\t\t<StateCode>PA</StateCode>\n" +
                "\t\t\t\t\t</ADDRESS>\n" +
                "\t\t\t\t\t<PROPERTY_DETAIL>\n" +
                "\t\t\t\t\t\t<FinancedUnitCount>2</FinancedUnitCount>\n" +
                "\t\t\t\t\t\t<PropertyStructureBuiltYear>2001</PropertyStructureBuiltYear>\n" +
                "\t\t\t\t\t\t<AttachmentType>Attached</AttachmentType>\n" +
                "\t\t\t\t\t\t<PropertyUsageType>InvestmentProperty</PropertyUsageType>\n" +
                "\t\t\t\t\t\t<ConstructionMethodType>Manufactured</ConstructionMethodType>\n" +
                "\t\t\t\t\t\t<EXTENSION>\n" +
                "\t\t\t\t\t\t\t<OTHER>\n" +
                "\t\t\t\t\t\t\t\t<PropertyCategoryTypeCode>Detached</PropertyCategoryTypeCode>\n" +
                "\t\t\t\t\t\t\t</OTHER>\n" +
                "\t\t\t\t\t\t</EXTENSION>\n" +
                "\t\t\t\t\t</PROPERTY_DETAIL>\n" +
                "\t\t\t\t\t<PROPERTY_VALUATIONS>\n" +
                "\t\t\t\t\t\t<PROPERTY_VALUATION>\n" +
                "\t\t\t\t\t\t\t<PROPERTY_VALUATION_DETAIL>\n" +
                "\t\t\t\t\t\t\t\t<PropertyValuationAmount>200000</PropertyValuationAmount>\n" +
                "\t\t\t\t\t\t\t\t<PropertyValuationEffectiveDate>2014-06-18</PropertyValuationEffectiveDate>\n" +
                "\t\t\t\t\t\t\t\t<PropertyValuationMethodType>PriorAppraisalUsed</PropertyValuationMethodType>\n" +
                "\t\t\t\t\t\t\t\t<PropertyValuationStateType>Original</PropertyValuationStateType>\n" +
                "\t\t\t\t\t\t\t</PROPERTY_VALUATION_DETAIL>\n" +
                "\t\t\t\t\t\t</PROPERTY_VALUATION>\n" +
                "\t\t\t\t\t</PROPERTY_VALUATIONS>\n" +
                "\t\t\t\t</SUBJECT_PROPERTY>\n" +
                "\t\t\t</COLLATERAL>\n" +
                "\t\t</COLLATERALS>\n" +
                "\t\t<LOAN>\n" +
                "\t\t\t<ADJUSTMENT>\n" +
                "\t\t\t\t<INTEREST_RATE_ADJUSTMENT>\n" +
                "\t\t\t\t\t<INDEX_RULES>\n" +
                "\t\t\t\t\t\t<INDEX_RULE>\n" +
                "\t\t\t\t\t\t\t<IndexSourceType>LIBOR</IndexSourceType>\n" +
                "\t\t\t\t\t\t\t<IndexTypeOtherDescription>LIBOR</IndexTypeOtherDescription>\n" +
                "\t\t\t\t\t\t</INDEX_RULE>\n" +
                "\t\t\t\t\t</INDEX_RULES>\n" +
                "\t\t\t\t\t<INTEREST_RATE_LIFETIME_ADJUSTMENT_RULE>\n" +
                "\t\t\t\t\t\t<FirstRateChangeMonthsCount>12</FirstRateChangeMonthsCount>\n" +
                "\t\t\t\t\t\t<CeilingRatePercent>8.8</CeilingRatePercent>\n" +
                "\t\t\t\t\t\t<MarginRatePercent>1.7</MarginRatePercent>\n" +
                "\t\t\t\t\t\t<MaximumIncreaseRatePercent>5</MaximumIncreaseRatePercent>\n" +
                "\t\t\t\t\t</INTEREST_RATE_LIFETIME_ADJUSTMENT_RULE>\n" +
                "\t\t\t\t\t<INTEREST_RATE_PER_CHANGE_ADJUSTMENT_RULES>\n" +
                "\t\t\t\t\t\t<INTEREST_RATE_PER_CHANGE_ADJUSTMENT_RULE>\n" +
                "\t\t\t\t\t\t\t<PerChangeCeilingRatePercent>7.7</PerChangeCeilingRatePercent>\n" +
                "\t\t\t\t\t\t\t<AdjustmentRuleType>Subsequent</AdjustmentRuleType>\n" +
                "\t\t\t\t\t\t\t<PerChangeRateAdjustmentFrequencyMonthsCount>3</PerChangeRateAdjustmentFrequencyMonthsCount>\n" +
                "\t\t\t\t\t\t</INTEREST_RATE_PER_CHANGE_ADJUSTMENT_RULE>\n" +
                "\t\t\t\t\t\t<!--<INTEREST_RATE_PER_CHANGE_ADJUSTMENT_RULE>\n" +
                "\t\t\t\t\t\t\t<AdjustmentRuleType>First</AdjustmentRuleType>\n" +
                "\t\t\t\t\t\t\t<PerChangeMaximumIncreaseRatePercent>5</PerChangeMaximumIncreaseRatePercent>\n" +
                "\t\t\t\t\t\t</INTEREST_RATE_PER_CHANGE_ADJUSTMENT_RULE>-->\n" +
                "\t\t\t\t\t</INTEREST_RATE_PER_CHANGE_ADJUSTMENT_RULES>\n" +
                "\t\t\t\t</INTEREST_RATE_ADJUSTMENT>\n" +
                "\t\t\t</ADJUSTMENT>\n" +
                "\t\t\t<AMORTIZATION>\n" +
                "\t\t\t\t<AMORTIZATION_RULE>\n" +
                "\t\t\t\t\t<AmortizationType>GEM</AmortizationType>\n" +
                "\t\t\t\t\t<LoanAmortizationPeriodType>Month</LoanAmortizationPeriodType>\n" +
                "\t\t\t\t\t<LoanAmortizationPeriodCount>360</LoanAmortizationPeriodCount>\n" +
                "\t\t\t\t</AMORTIZATION_RULE>\n" +
                "\t\t\t</AMORTIZATION>\n" +
                "\t\t\t<BALLOON>\n" +
                "\t\t\t\t<BalloonLoanMaturityTermMonthsCount>23</BalloonLoanMaturityTermMonthsCount>\n" +
                "\t\t\t</BALLOON>\n" +
                "\t\t\t<BUYDOWN>\n" +
                "\t\t\t\t<BUYDOWN_RULE>\n" +
                "\t\t\t\t\t<BuydownChangeFrequencyMonthsCount>12</BuydownChangeFrequencyMonthsCount>\n" +
                "\t\t\t\t\t<BuydownDurationMonthsCount>36</BuydownDurationMonthsCount>\n" +
                "\t\t\t\t\t<BuydownIncreaseRatePercent>1</BuydownIncreaseRatePercent>\n" +
                "\t\t\t\t</BUYDOWN_RULE>\n" +
                "\t\t\t</BUYDOWN>\n" +
                "\t\t\t<CERTIFICATE/>\n" +
                "\t\t\t<CLOSING_INFORMATION>\n" +
                "\t\t\t\t<CLOSING_COST_FUNDS>\n" +
                "\t\t\t\t\t<CLOSING_COST_FUND>\n" +
                "\t\t\t\t\t\t<ClosingCostFundAmount>10000</ClosingCostFundAmount>\n" +
                "\t\t\t\t\t\t<FundsType>GiftFunds</FundsType>\n" +
                "\t\t\t\t\t</CLOSING_COST_FUND>\n" +
                "\t\t\t\t</CLOSING_COST_FUNDS>\n" +
                "\t\t\t</CLOSING_INFORMATION>\n" +
                "\t\t\t<CONSTRUCTION>\n" +
                "\t\t\t\t<ConstructionLoanType>ConstructionToPermanent</ConstructionLoanType>\n" +
                "\t\t\t\t<ConstructionImprovementCostsAmount>25000</ConstructionImprovementCostsAmount>\n" +
                "\t\t\t</CONSTRUCTION>\n" +
                "\t\t\t<DOCUMENT_SPECIFIC_DATA_SETS>\n" +
                "\t\t\t\t<DOCUMENT_SPECIFIC_DATA_SET>\n" +
                "\t\t\t\t\t<URLA>\n" +
                "\t\t\t\t\t\t<URLA_DETAIL>\n" +
                "\t\t\t\t\t\t\t<AlterationsImprovementsAndRepairsAmount>2500.55</AlterationsImprovementsAndRepairsAmount>\n" +
                "\t\t\t\t\t\t\t<AlterationsImprovementsAndRepairsDate>2014-02-28T00:00:00</AlterationsImprovementsAndRepairsDate>\n" +
                "\t\t\t\t\t\t\t<BorrowerPaidDiscountPointsTotalAmount>2200.22</BorrowerPaidDiscountPointsTotalAmount>\n" +
                "\t\t\t\t\t\t\t<BorrowerRequestedInterestRatePercent>2</BorrowerRequestedInterestRatePercent>\n" +
                "\t\t\t\t\t\t\t<BorrowerRequestedLoanAmount>1500.55</BorrowerRequestedLoanAmount>\n" +
                "\t\t\t\t\t\t\t<EstimatedClosingCostsAmount>55000</EstimatedClosingCostsAmount>\n" +
                "\t\t\t\t\t\t\t<MIAndFundingFeeFinancedAmount>120500</MIAndFundingFeeFinancedAmount>\n" +
                "\t\t\t\t\t\t\t<MIAndFundingFeeTotalAmount>120300</MIAndFundingFeeTotalAmount>\n" +
                "\t\t\t\t\t\t\t<PrepaidItemsEstimatedAmount>1200</PrepaidItemsEstimatedAmount>\n" +
                "\t\t\t\t\t\t\t<PurchasePriceAmount>120000</PurchasePriceAmount>\n" +
                "\t\t\t\t\t\t\t<RefinanceIncludingDebtsToBePaidOffAmount>6500.65</RefinanceIncludingDebtsToBePaidOffAmount>\n" +
                "\t\t\t\t\t\t\t<SellerPaidClosingCostsAmount>7700.77</SellerPaidClosingCostsAmount>\n" +
                "\t\t\t\t\t\t</URLA_DETAIL>\n" +
                "\t\t\t\t\t\t<URLA_TOTAL_HOUSING_EXPENSES>\n" +
                "\t\t\t\t\t\t\t<URLA_TOTAL_HOUSING_EXPENSE>\n" +
                "\t\t\t\t\t\t\t\t<URLATotalHousingExpensePaymentAmount>2000</URLATotalHousingExpensePaymentAmount>\n" +
                "\t\t\t\t\t\t\t</URLA_TOTAL_HOUSING_EXPENSE>\n" +
                "\t\t\t\t\t\t</URLA_TOTAL_HOUSING_EXPENSES>\n" +
                "\t\t\t\t\t</URLA>\n" +
                "\t\t\t\t</DOCUMENT_SPECIFIC_DATA_SET>\n" +
                "\t\t\t</DOCUMENT_SPECIFIC_DATA_SETS>\n" +
                "\t\t\t<DOCUMENTATIONS>\n" +
                "\t\t\t\t<DOCUMENTATION>\n" +
                "\t\t\t\t\t<AssetDocumentationLevelIdentifier>Asset123</AssetDocumentationLevelIdentifier>\n" +
                "\t\t\t\t</DOCUMENTATION>\n" +
                "\t\t\t\t<DOCUMENTATION>\n" +
                "\t\t\t\t\t<EmploymentDocumentationLevelIdentifier>Emp123</EmploymentDocumentationLevelIdentifier>\n" +
                "\t\t\t\t</DOCUMENTATION>\n" +
                "\t\t\t\t<DOCUMENTATION>\n" +
                "\t\t\t\t\t<IncomeDocumentationLevelIdentifier>Income123</IncomeDocumentationLevelIdentifier>\n" +
                "\t\t\t\t</DOCUMENTATION>\n" +
                "\t\t\t</DOCUMENTATIONS>\n" +
                "\t\t\t<DOWN_PAYMENTS>\n" +
                "\t\t\t\t<DOWN_PAYMENT>\n" +
                "\t\t\t\t\t<EXTENSION>\n" +
                "\t\t\t\t\t\t<OTHER>\n" +
                "\t\t\t\t\t\t\t<FundsMinimumThresholdAchievedIndicator>true</FundsMinimumThresholdAchievedIndicator>\n" +
                "\t\t\t\t\t\t</OTHER>\n" +
                "\t\t\t\t\t</EXTENSION>\n" +
                "\t\t\t\t</DOWN_PAYMENT>\n" +
                "\t\t\t</DOWN_PAYMENTS>\n" +
                "\t\t\t<HOUSING_EXPENSES>\n" +
                "\t\t\t\t<HOUSING_EXPENSE>\n" +
                "\t\t\t\t\t<HousingExpenseTypeOtherDescription>otherHousing</HousingExpenseTypeOtherDescription>\n" +
                "\t\t\t\t\t<HousingExpensePaymentAmount>12322</HousingExpensePaymentAmount>\n" +
                "\t\t\t\t\t<HousingExpensePaymentAmountType>Proposed</HousingExpensePaymentAmountType>\n" +
                "\t\t\t\t\t<HousingExpenseType>FirstMortgagePITI</HousingExpenseType>\n" +
                "\t\t\t\t</HOUSING_EXPENSE>\n" +
                "\t\t\t</HOUSING_EXPENSES>\n" +
                "\t\t\t<INTEREST_ONLY>\n" +
                "\t\t\t\t<InterestOnlyTermMonthsCount>24</InterestOnlyTermMonthsCount>\n" +
                "\t\t\t</INTEREST_ONLY>\n" +
                "\t\t\t<LOAN_DETAIL>\n" +
                "\t\t\t\t<ApplicationReceivedDate>2014-06-18</ApplicationReceivedDate>\n" +
                "\t\t\t\t<BalloonIndicator>true</BalloonIndicator>\n" +
                "\t\t\t\t<BuydownTemporarySubsidyFundingIndicator>true</BuydownTemporarySubsidyFundingIndicator>\n" +
                "\t\t\t\t<InterestOnlyIndicator>true</InterestOnlyIndicator>\n" +
                "\t\t\t\t<RelocationLoanIndicator>true</RelocationLoanIndicator>\n" +
                "\t\t\t\t<LoanRepaymentType>ConstantPrincipal</LoanRepaymentType>\n" +
                "\t\t\t\t<NegativeAmortizationIndicator>true</NegativeAmortizationIndicator>\n" +
                "\t\t\t\t<QualifiedMortgageIndicator>true</QualifiedMortgageIndicator>\n" +
                "\t\t\t\t<EXTENSION>\n" +
                "\t\t\t\t\t<OTHER>\n" +
                "\t\t\t\t\t\t<ProductTypeCode>A</ProductTypeCode>\n" +
                "\t\t\t\t\t</OTHER>\n" +
                "\t\t\t\t</EXTENSION>\n" +
                "\t\t\t</LOAN_DETAIL>\n" +
                "\t\t\t<LOAN_IDENTIFIERS>\n" +
                "\t\t\t\t<LOAN_IDENTIFIER>\n" +
                "\t\t\t\t\t<LoanIdentifier>200</LoanIdentifier>\n" +
                "\t\t\t\t\t<LoanIdentifierType>LenderCase</LoanIdentifierType>\n" +
                "\t\t\t\t</LOAN_IDENTIFIER>\n" +
                "\t\t\t\t<LOAN_IDENTIFIER>\n" +
                "\t\t\t\t\t<LoanIdentifier>55555555</LoanIdentifier>\n" +
                "\t\t\t\t\t<LoanIdentifierType>InvestorLoan</LoanIdentifierType>\n" +
                "\t\t\t\t</LOAN_IDENTIFIER>\n" +
                "\t\t\t</LOAN_IDENTIFIERS>\n" +
                "\t\t\t<LOAN_LEVEL_CREDIT>\n" +
                "\t\t\t\t<LOAN_LEVEL_CREDIT_DETAIL>\n" +
                "\t\t\t\t\t<CreditReferenceType>NonTraditional</CreditReferenceType>\n" +
                "\t\t\t\t</LOAN_LEVEL_CREDIT_DETAIL>\n" +
                "\t\t\t</LOAN_LEVEL_CREDIT>\n" +
                "\t\t\t<LTV>\n" +
                "\t\t\t\t<BaseLTVRatioPercent>15.55</BaseLTVRatioPercent>\n" +
                "\t\t\t\t<LTVRatioPercent>10.11</LTVRatioPercent>\n" +
                "\t\t\t</LTV>\n" +
                "\t\t\t<PAYMENT>\n" +
                "\t\t\t\t<PAYMENT_RULE>\n" +
                "\t\t\t\t\t<PaymentFrequencyType>Biweekly</PaymentFrequencyType>\n" +
                "\t\t\t\t\t<InitialPrincipalAndInterestPaymentAmount>1419.81</InitialPrincipalAndInterestPaymentAmount>\n" +
                "\t\t\t\t\t<InitialPITIPaymentAmount>2419.81</InitialPITIPaymentAmount>\n" +
                "\t\t\t\t</PAYMENT_RULE>\n" +
                "\t\t\t</PAYMENT>\n" +
                "\t\t\t<QUALIFICATION>\n" +
                "\t\t\t\t<QualifyingRatePercent>2</QualifyingRatePercent>\n" +
                "\t\t\t\t<TotalDebtExpenseRatioPercent>5.69</TotalDebtExpenseRatioPercent>\n" +
                "\t\t\t\t<BorrowerReservesMonthlyPaymentCount>30</BorrowerReservesMonthlyPaymentCount>\n" +
                "\t\t\t\t<HousingExpenseRatioPercent>8.8</HousingExpenseRatioPercent>\n" +
                "\t\t\t</QUALIFICATION>\n" +
                "\t\t\t<REFINANCE>\n" +
                "\t\t\t\t<RefinanceCashOutDeterminationType>LimitedCashOut</RefinanceCashOutDeterminationType>\n" +
                "\t\t\t\t<RefinancePrimaryPurposeType>DebtConsolidation</RefinancePrimaryPurposeType>\n" +
                "\t\t\t\t<TotalPriorLienPayoffAmount>7800</TotalPriorLienPayoffAmount>\n" +
                "\t\t\t</REFINANCE>\n" +
                "\t\t\t<TERMS_OF_LOAN>\n" +
                "\t\t\t\t<NoteAmount>87000</NoteAmount>\n" +
                "\t\t\t\t<NoteRatePercent>3.45</NoteRatePercent>\n" +
                "\t\t\t\t<BaseLoanAmount>1000000</BaseLoanAmount>\n" +
                "\t\t\t\t<LoanPurposeType>Refinance</LoanPurposeType>\n" +
                "\t\t\t\t<LienPriorityType>FourthLien</LienPriorityType>\n" +
                "\t\t\t\t<MortgageType>PublicAndIndianHousing</MortgageType>\n" +
                "\t\t\t\t<LoanPurposeType>MortgageModification</LoanPurposeType>\n" +
                "\t\t\t\t<LoanPurposeTypeOtherDescription>testLoanPurpose</LoanPurposeTypeOtherDescription>\n" +
                "\t\t\t\t<DisclosedIndexRatePercent>8.56</DisclosedIndexRatePercent>\n" +
                "\t\t\t</TERMS_OF_LOAN>\n" +
                "\t\t\t<EXTENSION>\n" +
                "\t\t\t\t<OTHER>\n" +
                "\t\t\t\t\t<COMBINED_LTVS>\n" +
                "\t\t\t\t\t\t<COMBINED_LTV>\n" +
                "\t\t\t\t\t\t\t<HomeEquityCombinedLTVRatioPercent>14.44</HomeEquityCombinedLTVRatioPercent>\n" +
                "\t\t\t\t\t\t\t<CombinedLTVRatioPercent>90</CombinedLTVRatioPercent>\n" +
                "\t\t\t\t\t\t</COMBINED_LTV>\n" +
                "\t\t\t\t\t</COMBINED_LTVS>\n" +
                "\t\t\t\t</OTHER>\n" +
                "\t\t\t</EXTENSION>\n" +
                "\t\t\t<UNDERWRITING>\n" +
                "\t\t\t\t<AUTOMATED_UNDERWRITINGS>\n" +
                "\t\t\t\t\t<AUTOMATED_UNDERWRITING>\n" +
                "\t\t\t\t\t\t<LoanProspectorCreditRiskClassificationDescription>Accept</LoanProspectorCreditRiskClassificationDescription>\n" +
                "\t\t\t\t\t\t<FREPurchaseEligibilityType>FreddieMacEligible</FREPurchaseEligibilityType>\n" +
                "\t\t\t\t\t\t<AutomatedUnderwritingCaseIdentifier>Case123</AutomatedUnderwritingCaseIdentifier>\n" +
                "\t\t\t\t\t\t<AutomatedUnderwritingDecisionDatetime>2014-06-20</AutomatedUnderwritingDecisionDatetime>\n" +
                "\t\t\t\t\t</AUTOMATED_UNDERWRITING>\n" +
                "\t\t\t\t</AUTOMATED_UNDERWRITINGS>\n" +
                "\t\t\t\t<UNDERWRITING_DETAIL>\n" +
                "\t\t\t\t\t<LoanManualUnderwritingIndicatorContractUnderwritingIndicator>Automated</LoanManualUnderwritingIndicatorContractUnderwritingIndicator>\n" +
                "\t\t\t\t\t<LoanManualUnderwritingIndicator>false</LoanManualUnderwritingIndicator>\n" +
                "\t\t\t\t</UNDERWRITING_DETAIL>\n" +
                "\t\t\t</UNDERWRITING>\n" +
                "\t\t</LOAN>\n" +
                "\t\t<PARTIES>\n" +
                "\t\t\t<PARTY>\n" +
                "\t\t\t\t<INDIVIDUAL>\n" +
                "\t\t\t\t\t<NAME>\n" +
                "\t\t\t\t\t\t<FirstName>primary</FirstName>\n" +
                "\t\t\t\t\t\t<LastName>borrower</LastName>\n" +
                "\t\t\t\t\t\t<MiddleName>peter</MiddleName>\n" +
                "\t\t\t\t\t\t<SuffixName>jt</SuffixName>\n" +
                "\t\t\t\t\t\t<FullName>PB</FullName>\n" +
                "\t\t\t\t\t\t<PrefixName>Pre</PrefixName>\n" +
                "\t\t\t\t\t\t<SuffixName>Suf</SuffixName>\n" +
                "\t\t\t\t\t</NAME>\n" +
                "\t\t\t\t</INDIVIDUAL>\n" +
                "\t\t\t\t<ADDRESSES>\n" +
                "\t\t\t\t\t<ADDRESS>\n" +
                "\t\t\t\t\t\t<AddressType>Mailing</AddressType>\n" +
                "\t\t\t\t\t\t<AddressLineText>BB80 street</AddressLineText>\n" +
                "\t\t\t\t\t\t<AddressAdditionalLineText>Additionaltext</AddressAdditionalLineText>\n" +
                "\t\t\t\t\t\t<CityName>City</CityName>\n" +
                "\t\t\t\t\t\t<PostalCode>48126</PostalCode>\n" +
                "\t\t\t\t\t\t<StateCode>MI</StateCode>\n" +
                "\t\t\t\t\t</ADDRESS>\n" +
                "\t\t\t\t\t<ADDRESS>\n" +
                "\t\t\t\t\t\t<AddressType>Current</AddressType>\n" +
                "\t\t\t\t\t\t<AddressLineText>BB80 street</AddressLineText>\n" +
                "\t\t\t\t\t\t<AddressAdditionalLineText>Additionaltext</AddressAdditionalLineText>\n" +
                "\t\t\t\t\t\t<CityName>City</CityName>\n" +
                "\t\t\t\t\t\t<PostalCode>48126</PostalCode>\n" +
                "\t\t\t\t\t\t<StateCode>MI</StateCode>\n" +
                "\t\t\t\t\t</ADDRESS>\n" +
                "\t\t\t\t</ADDRESSES>\n" +
                "\t\t\t\t<ROLES>\n" +
                "\t\t\t\t\t<ROLE>\n" +
                "\t\t\t\t\t\t<BORROWER>\n" +
                "\t\t\t\t\t\t\t<DECLARATION>\n" +
                "\t\t\t\t\t\t\t\t<DECLARATION_DETAIL>\n" +
                "\t\t\t\t\t\t\t\t\t<AlimonyChildSupportObligationIndicator>true</AlimonyChildSupportObligationIndicator>\n" +
                "\t\t\t\t\t\t\t\t\t<BankruptcyIndicator>false</BankruptcyIndicator>\n" +
                "\t\t\t\t\t\t\t\t\t<BorrowedDownPaymentIndicator>false</BorrowedDownPaymentIndicator>\n" +
                "\t\t\t\t\t\t\t\t\t<BorrowerFirstTimeHomebuyerIndicator>false</BorrowerFirstTimeHomebuyerIndicator>\n" +
                "\t\t\t\t\t\t\t\t\t<CitizenshipResidencyType>USCitizen</CitizenshipResidencyType>\n" +
                "\t\t\t\t\t\t\t\t\t<CoMakerEndorserOfNoteIndicator>false</CoMakerEndorserOfNoteIndicator>\n" +
                "\t\t\t\t\t\t\t\t\t<HomeownerPastThreeYearsType>Yes</HomeownerPastThreeYearsType>\n" +
                "\t\t\t\t\t\t\t\t\t<IntentToOccupyType>Yes</IntentToOccupyType>\n" +
                "\t\t\t\t\t\t\t\t\t<LoanForeclosureOrJudgmentIndicator>false</LoanForeclosureOrJudgmentIndicator>\n" +
                "\t\t\t\t\t\t\t\t\t<OutstandingJudgmentsIndicator>false</OutstandingJudgmentsIndicator>\n" +
                "\t\t\t\t\t\t\t\t\t<PartyToLawsuitIndicator>false</PartyToLawsuitIndicator>\n" +
                "\t\t\t\t\t\t\t\t\t<PresentlyDelinquentIndicator>false</PresentlyDelinquentIndicator>\n" +
                "\t\t\t\t\t\t\t\t\t<PriorPropertyTitleType>JointWithSpouse</PriorPropertyTitleType>\n" +
                "\t\t\t\t\t\t\t\t\t<PriorPropertyUsageType>PrimaryResidence</PriorPropertyUsageType>\n" +
                "\t\t\t\t\t\t\t\t\t<PropertyForeclosedPastSevenYearsIndicator>false</PropertyForeclosedPastSevenYearsIndicator>\n" +
                "\t\t\t\t\t\t\t\t</DECLARATION_DETAIL>\n" +
                "\t\t\t\t\t\t\t</DECLARATION>\n" +
                "\t\t\t\t\t\t\t<BORROWER_DETAIL>\n" +
                "\t\t\t\t\t\t\t\t<DependentCount>4</DependentCount>\n" +
                "\t\t\t\t\t\t\t\t<BorrowerClassificationType>Primary</BorrowerClassificationType>\n" +
                "\t\t\t\t\t\t\t\t<BorrowerMailToAddressSameAsPropertyIndicator>true</BorrowerMailToAddressSameAsPropertyIndicator>\n" +
                "\t\t\t\t\t\t\t\t<BorrowerBirthDate>1984-02-28</BorrowerBirthDate>\n" +
                "\t\t\t\t\t\t\t\t<SchoolingYearsCount>10</SchoolingYearsCount>\n" +
                "\t\t\t\t\t\t\t\t<MaritalStatusType>Single</MaritalStatusType>\n" +
                "\t\t\t\t\t\t\t\t<BorrowerApplicationSignedDate>2014-02-28</BorrowerApplicationSignedDate>\n" +
                "\t\t\t\t\t\t\t\t<EXTENSION>\n" +
                "\t\t\t\t\t\t\t\t\t<OTHER>\n" +
                "\t\t\t\t\t\t\t\t\t\t<NonOccupantIndicator>true</NonOccupantIndicator>\n" +
                "\t\t\t\t\t\t\t\t\t</OTHER>\n" +
                "\t\t\t\t\t\t\t\t</EXTENSION>\n" +
                "\t\t\t\t\t\t\t</BORROWER_DETAIL>\n" +
                "\t\t\t\t\t\t\t<CREDIT_SCORES>\n" +
                "\t\t\t\t\t\t\t\t<CREDIT_SCORE>\n" +
                "\t\t\t\t\t\t\t\t\t<CREDIT_SCORE_DETAIL>\n" +
                "\t\t\t\t\t\t\t\t\t\t<CreditRepositorySourceType>Equifax</CreditRepositorySourceType>\n" +
                "\t\t\t\t\t\t\t\t\t\t<CreditReportType>NonTraditional</CreditReportType>\n" +
                "\t\t\t\t\t\t\t\t\t\t<CreditScoreDate>2013-02-28T00:00:00</CreditScoreDate>\n" +
                "\t\t\t\t\t\t\t\t\t\t<CreditScoreValue>720</CreditScoreValue>\n" +
                "\t\t\t\t\t\t\t\t\t</CREDIT_SCORE_DETAIL>\n" +
                "\t\t\t\t\t\t\t\t</CREDIT_SCORE>\n" +
                "\t\t\t\t\t\t\t</CREDIT_SCORES>\n" +
                "\t\t\t\t\t\t\t<CURRENT_INCOME>\n" +
                "\t\t\t\t\t\t\t\t<CURRENT_INCOME_ITEMS>\n" +
                "\t\t\t\t\t\t\t\t\t<CURRENT_INCOME_ITEM>\n" +
                "\t\t\t\t\t\t\t\t\t\t<CURRENT_INCOME_ITEM_DETAIL>\n" +
                "\t\t\t\t\t\t\t\t\t\t\t<CurrentIncomeMonthlyTotalAmount>3500</CurrentIncomeMonthlyTotalAmount>\n" +
                "\t\t\t\t\t\t\t\t\t\t\t<IncomeType>Base</IncomeType>\n" +
                "\t\t\t\t\t\t\t\t\t\t\t<IncomeTypeOtherDescription>Base</IncomeTypeOtherDescription>\n" +
                "\t\t\t\t\t\t\t\t\t\t</CURRENT_INCOME_ITEM_DETAIL>\n" +
                "\t\t\t\t\t\t\t\t\t</CURRENT_INCOME_ITEM>\n" +
                "\t\t\t\t\t\t\t\t</CURRENT_INCOME_ITEMS>\n" +
                "\t\t\t\t\t\t\t\t<CURRENT_INCOME_DETAIL>\n" +
                "\t\t\t\t\t\t\t\t\t<URLABorrowerTotalMonthlyIncomeAmount>1230</URLABorrowerTotalMonthlyIncomeAmount>\n" +
                "\t\t\t\t\t\t\t\t</CURRENT_INCOME_DETAIL>\n" +
                "\t\t\t\t\t\t\t</CURRENT_INCOME>\n" +
                "\t\t\t\t\t\t\t<EMPLOYERS>\n" +
                "\t\t\t\t\t\t\t\t<EMPLOYER>\n" +
                "\t\t\t\t\t\t\t\t\t<LEGAL_ENTITY>\n" +
                "\t\t\t\t\t\t\t\t\t\t<LEGAL_ENTITY_DETAIL>\n" +
                "\t\t\t\t\t\t\t\t\t\t\t<FullName>Employername</FullName>\n" +
                "\t\t\t\t\t\t\t\t\t\t</LEGAL_ENTITY_DETAIL>\n" +
                "\t\t\t\t\t\t\t\t\t</LEGAL_ENTITY>\n" +
                "\t\t\t\t\t\t\t\t\t<EMPLOYMENT>\n" +
                "\t\t\t\t\t\t\t\t\t\t<EmploymentBorrowerSelfEmployedIndicator>true</EmploymentBorrowerSelfEmployedIndicator>\n" +
                "\t\t\t\t\t\t\t\t\t\t<EmploymentStatusType>Current</EmploymentStatusType>\n" +
                "\t\t\t\t\t\t\t\t\t\t<EmploymentClassificationType>Secondary</EmploymentClassificationType>\n" +
                "\t\t\t\t\t\t\t\t\t\t<EmploymentPositionDescription>Sr Supervisor</EmploymentPositionDescription>\n" +
                "\t\t\t\t\t\t\t\t\t\t<EmploymentTimeInLineOfWorkMonthsCount>5</EmploymentTimeInLineOfWorkMonthsCount>\n" +
                "\t\t\t\t\t\t\t\t\t\t<EmploymentYearsOnJobCount>12</EmploymentYearsOnJobCount>\n" +
                "\t\t\t\t\t\t\t\t\t\t<EmploymentMonthlyIncomeAmount>5500</EmploymentMonthlyIncomeAmount>\n" +
                "\t\t\t\t\t\t\t\t\t</EMPLOYMENT>\n" +
                "\t\t\t\t\t\t\t\t</EMPLOYER>\n" +
                "\t\t\t\t\t\t\t</EMPLOYERS>\n" +
                "\t\t\t\t\t\t\t<GOVERNMENT_MONITORING>\n" +
                "\t\t\t\t\t\t\t\t<GOVERNMENT_MONITORING_DETAIL>\n" +
                "\t\t\t\t\t\t\t\t\t<GenderType>Female</GenderType>\n" +
                "\t\t\t\t\t\t\t\t\t<HMDAEthnicityType>HispanicOrLatino</HMDAEthnicityType>\n" +
                "\t\t\t\t\t\t\t\t\t<RaceNationalOriginRefusalIndicator>true</RaceNationalOriginRefusalIndicator>\n" +
                "\t\t\t\t\t\t\t\t</GOVERNMENT_MONITORING_DETAIL>\n" +
                "\t\t\t\t\t\t\t\t<HMDA_RACES>\n" +
                "\t\t\t\t\t\t\t\t\t<HMDA_RACE>\n" +
                "\t\t\t\t\t\t\t\t\t\t<HMDARaceType>AmericanIndianOrAlaskaNative</HMDARaceType>\n" +
                "\t\t\t\t\t\t\t\t\t</HMDA_RACE>\n" +
                "\t\t\t\t\t\t\t\t\t<HMDA_RACE>\n" +
                "\t\t\t\t\t\t\t\t\t\t<HMDARaceType>Asian</HMDARaceType>\n" +
                "\t\t\t\t\t\t\t\t\t</HMDA_RACE>\n" +
                "\t\t\t\t\t\t\t\t</HMDA_RACES>\n" +
                "\t\t\t\t\t\t\t</GOVERNMENT_MONITORING>\n" +
                "\t\t\t\t\t\t\t<MILITARY_SERVICES>\n" +
                "\t\t\t\t\t\t\t\t<MILITARY_SERVICE>\n" +
                "\t\t\t\t\t\t\t\t\t<MilitaryStatusType>ActiveDuty</MilitaryStatusType>\n" +
                "\t\t\t\t\t\t\t\t</MILITARY_SERVICE>\n" +
                "\t\t\t\t\t\t\t</MILITARY_SERVICES>\n" +
                "\t\t\t\t\t\t\t<RESIDENCES>\n" +
                "\t\t\t\t\t\t\t\t<RESIDENCE>\n" +
                "\t\t\t\t\t\t\t\t\t<ADDRESS>\n" +
                "\t\t\t\t\t\t\t\t\t\t<AddressType>Mailing</AddressType>\n" +
                "\t\t\t\t\t\t\t\t\t\t<AddressLineText>BB80 street</AddressLineText>\n" +
                "\t\t\t\t\t\t\t\t\t\t<AddressAdditionalLineText>Additionaltext</AddressAdditionalLineText>\n" +
                "\t\t\t\t\t\t\t\t\t\t<CityName>City</CityName>\n" +
                "\t\t\t\t\t\t\t\t\t\t<PostalCode>48126</PostalCode>\n" +
                "\t\t\t\t\t\t\t\t\t\t<StateCode>MI</StateCode>\n" +
                "\t\t\t\t\t\t\t\t\t</ADDRESS>\n" +
                "\t\t\t\t\t\t\t\t\t<RESIDENCE_DETAIL>\n" +
                "\t\t\t\t\t\t\t\t\t\t<BorrowerResidencyType>Current</BorrowerResidencyType>\n" +
                "\t\t\t\t\t\t\t\t\t</RESIDENCE_DETAIL>\n" +
                "\t\t\t\t\t\t\t\t</RESIDENCE>\n" +
                "\t\t\t\t\t\t\t</RESIDENCES>\n" +
                "\t\t\t\t\t\t\t<SUMMARIES>\n" +
                "\t\t\t\t\t\t\t\t<SUMMARY>\n" +
                "\t\t\t\t\t\t\t\t\t<SummaryAmount>12321</SummaryAmount>\n" +
                "\t\t\t\t\t\t\t\t\t<SummaryAmountType>SubtotalLiquidAssetsNotIncludingGift</SummaryAmountType>\n" +
                "\t\t\t\t\t\t\t\t</SUMMARY>\n" +
                "\t\t\t\t\t\t\t</SUMMARIES>\n" +
                "\t\t\t\t\t\t</BORROWER>\n" +
                "\t\t\t\t\t\t<ROLE_DETAIL>\n" +
                "\t\t\t\t\t\t\t<PartyRoleType>Borrower</PartyRoleType>\n" +
                "\t\t\t\t\t\t</ROLE_DETAIL>\n" +
                "\t\t\t\t\t</ROLE>\n" +
                "\t\t\t\t</ROLES>\n" +
                "\t\t\t\t<TAXPAYER_IDENTIFIERS>\n" +
                "\t\t\t\t\t<TAXPAYER_IDENTIFIER>\n" +
                "\t\t\t\t\t\t<TaxpayerIdentifierType>SocialSecurityNumber</TaxpayerIdentifierType>\n" +
                "\t\t\t\t\t\t<TaxpayerIdentifierValue>111111111</TaxpayerIdentifierValue>\n" +
                "\t\t\t\t\t</TAXPAYER_IDENTIFIER>\n" +
                "\t\t\t\t</TAXPAYER_IDENTIFIERS>\n" +
                "\t\t\t</PARTY>\n" +
                "\t\t\t<PARTY>\n" +
                "\t\t\t\t<INDIVIDUAL>\n" +
                "\t\t\t\t\t<NAME>\n" +
                "\t\t\t\t\t\t<FirstName>seconday</FirstName>\n" +
                "\t\t\t\t\t\t<LastName>borrower</LastName>\n" +
                "\t\t\t\t\t\t<MiddleName>peter</MiddleName>\n" +
                "\t\t\t\t\t\t<FullName>SB</FullName>\n" +
                "\t\t\t\t\t\t<PrefixName>Pre</PrefixName>\n" +
                "\t\t\t\t\t\t<SuffixName>jt</SuffixName>\n" +
                "\t\t\t\t\t</NAME>\n" +
                "\t\t\t\t</INDIVIDUAL>\n" +
                "\t\t\t\t<ADDRESSES>\n" +
                "\t\t\t\t\t<ADDRESS>\n" +
                "\t\t\t\t\t\t<AddressType>Mailing</AddressType>\n" +
                "\t\t\t\t\t\t<AddressLineText>123 h r</AddressLineText>\n" +
                "\t\t\t\t\t\t<AddressAdditionalLineText>BB80-5080604C45FE</AddressAdditionalLineText>\n" +
                "\t\t\t\t\t\t<CityName>chi</CityName>\n" +
                "\t\t\t\t\t\t<PostalCode>12321</PostalCode>\n" +
                "\t\t\t\t\t\t<StateCode>PA</StateCode>\n" +
                "\t\t\t\t\t</ADDRESS>\n" +
                "\t\t\t\t</ADDRESSES>\n" +
                "\t\t\t\t<ROLES>\n" +
                "\t\t\t\t\t<ROLE>\n" +
                "\t\t\t\t\t\t<BORROWER>\n" +
                "\t\t\t\t\t\t\t<EMPLOYERS>\n" +
                "\t\t\t\t\t\t\t\t<EMPLOYER>\n" +
                "\t\t\t\t\t\t\t\t\t<LEGAL_ENTITY>\n" +
                "\t\t\t\t\t\t\t\t\t\t<LEGAL_ENTITY_DETAIL>\n" +
                "\t\t\t\t\t\t\t\t\t\t\t<FullName>EmployernameSB</FullName>\n" +
                "\t\t\t\t\t\t\t\t\t\t</LEGAL_ENTITY_DETAIL>\n" +
                "\t\t\t\t\t\t\t\t\t</LEGAL_ENTITY>\n" +
                "\t\t\t\t\t\t\t\t\t<EMPLOYMENT>\n" +
                "\t\t\t\t\t\t\t\t\t\t<EmploymentBorrowerSelfEmployedIndicator>true</EmploymentBorrowerSelfEmployedIndicator>\n" +
                "\t\t\t\t\t\t\t\t\t\t<EmploymentStatusType>previous</EmploymentStatusType>\n" +
                "\t\t\t\t\t\t\t\t\t\t<EmploymentClassificationType>Primary</EmploymentClassificationType>\n" +
                "\t\t\t\t\t\t\t\t\t\t<EmploymentPositionDescription>Jr</EmploymentPositionDescription>\n" +
                "\t\t\t\t\t\t\t\t\t\t<EmploymentTimeInLineOfYearsWorkCount>6</EmploymentTimeInLineOfYearsWorkCount>\n" +
                "\t\t\t\t\t\t\t\t\t\t<EmploymentYearsOnJobCount>10</EmploymentYearsOnJobCount>\n" +
                "\t\t\t\t\t\t\t\t\t\t<EmploymentMonthlyIncomeAmount>5200</EmploymentMonthlyIncomeAmount>\n" +
                "\t\t\t\t\t\t\t\t\t</EMPLOYMENT>\n" +
                "\t\t\t\t\t\t\t\t</EMPLOYER>\n" +
                "\t\t\t\t\t\t\t</EMPLOYERS>\n" +
                "\t\t\t\t\t\t\t<BORROWER_DETAIL>\n" +
                "\t\t\t\t\t\t\t\t<BorrowerBirthDate>1984-10-28</BorrowerBirthDate>\n" +
                "\t\t\t\t\t\t\t\t<SchoolingYearsCount>12</SchoolingYearsCount>\n" +
                "\t\t\t\t\t\t\t\t<MaritalStatusType>Married</MaritalStatusType>\n" +
                "\t\t\t\t\t\t\t\t<BorrowerMailToAddressSameAsPropertyIndicator>true</BorrowerMailToAddressSameAsPropertyIndicator>\n" +
                "\t\t\t\t\t\t\t\t<BorrowerApplicationSignedDate>2014-03-28</BorrowerApplicationSignedDate>\n" +
                "\t\t\t\t\t\t\t\t<BorrowerClassificationType>Secondary</BorrowerClassificationType>\n" +
                "\t\t\t\t\t\t\t\t<EXTENSION>\n" +
                "\t\t\t\t\t\t\t\t\t<OTHER>\n" +
                "\t\t\t\t\t\t\t\t\t\t<NonOccupantIndicator>true</NonOccupantIndicator>\n" +
                "\t\t\t\t\t\t\t\t\t</OTHER>\n" +
                "\t\t\t\t\t\t\t\t</EXTENSION>\n" +
                "\t\t\t\t\t\t\t</BORROWER_DETAIL>\n" +
                "\t\t\t\t\t\t\t<CREDIT_SCORES>\n" +
                "\t\t\t\t\t\t\t\t<CREDIT_SCORE>\n" +
                "\t\t\t\t\t\t\t\t\t<CREDIT_SCORE_DETAIL>\n" +
                "\t\t\t\t\t\t\t\t\t\t<CreditRepositorySourceType>Equifax</CreditRepositorySourceType>\n" +
                "\t\t\t\t\t\t\t\t\t\t<CreditReportType>NonTraditional</CreditReportType>\n" +
                "\t\t\t\t\t\t\t\t\t\t<CreditScoreDate>2014-02-28T00:00:00</CreditScoreDate>\n" +
                "\t\t\t\t\t\t\t\t\t\t<CreditScoreValue>800</CreditScoreValue>\n" +
                "\t\t\t\t\t\t\t\t\t</CREDIT_SCORE_DETAIL>\n" +
                "\t\t\t\t\t\t\t\t</CREDIT_SCORE>\n" +
                "\t\t\t\t\t\t\t</CREDIT_SCORES>\n" +
                "\t\t\t\t\t\t\t<CURRENT_INCOME>\n" +
                "\t\t\t\t\t\t\t\t<CURRENT_INCOME_ITEMS>\n" +
                "\t\t\t\t\t\t\t\t\t<CURRENT_INCOME_ITEM>\n" +
                "\t\t\t\t\t\t\t\t\t\t<CURRENT_INCOME_ITEM_DETAIL>\n" +
                "\t\t\t\t\t\t\t\t\t\t\t<CurrentIncomeMonthlyTotalAmount>3700</CurrentIncomeMonthlyTotalAmount>\n" +
                "\t\t\t\t\t\t\t\t\t\t\t<IncomeType>Bonus</IncomeType>\n" +
                "\t\t\t\t\t\t\t\t\t\t\t<IncomeTypeOtherDescription>Base</IncomeTypeOtherDescription>\n" +
                "\t\t\t\t\t\t\t\t\t\t</CURRENT_INCOME_ITEM_DETAIL>\n" +
                "\t\t\t\t\t\t\t\t\t</CURRENT_INCOME_ITEM>\n" +
                "\t\t\t\t\t\t\t\t</CURRENT_INCOME_ITEMS>\n" +
                "\t\t\t\t\t\t\t\t<CURRENT_INCOME_DETAIL>\n" +
                "\t\t\t\t\t\t\t\t\t<URLABorrowerTotalMonthlyIncomeAmount>1232</URLABorrowerTotalMonthlyIncomeAmount>\n" +
                "\t\t\t\t\t\t\t\t</CURRENT_INCOME_DETAIL>\n" +
                "\t\t\t\t\t\t\t</CURRENT_INCOME>\n" +
                "\t\t\t\t\t\t\t<RESIDENCES>\n" +
                "\t\t\t\t\t\t\t\t<RESIDENCE>\n" +
                "\t\t\t\t\t\t\t\t\t<ADDRESS>\n" +
                "\t\t\t\t\t\t\t\t\t\t<AddressType>Mailing</AddressType>\n" +
                "\t\t\t\t\t\t\t\t\t\t<AddressAdditionalLineText>BB80-5080604C45FE</AddressAdditionalLineText>\n" +
                "\t\t\t\t\t\t\t\t\t\t<AddressLineText>C64447B8-F4F2-4975-BB80-5080604C45FE</AddressLineText>\n" +
                "\t\t\t\t\t\t\t\t\t\t<CityName>6F938252-8C4A-4F5D-8EE0-DDC7D1C50B46</CityName>\n" +
                "\t\t\t\t\t\t\t\t\t\t<PostalCode>48126</PostalCode>\n" +
                "\t\t\t\t\t\t\t\t\t\t<StateCode>MI</StateCode>\n" +
                "\t\t\t\t\t\t\t\t\t</ADDRESS>\n" +
                "\t\t\t\t\t\t\t\t\t<RESIDENCE_DETAIL>\n" +
                "\t\t\t\t\t\t\t\t\t\t<BorrowerResidencyType>Current</BorrowerResidencyType>\n" +
                "\t\t\t\t\t\t\t\t\t</RESIDENCE_DETAIL>\n" +
                "\t\t\t\t\t\t\t\t</RESIDENCE>\n" +
                "\t\t\t\t\t\t\t</RESIDENCES>\n" +
                "\t\t\t\t\t\t\t<GOVERNMENT_MONITORING>\n" +
                "\t\t\t\t\t\t\t\t<GOVERNMENT_MONITORING_DETAIL>\n" +
                "\t\t\t\t\t\t\t\t\t<GenderType>Male</GenderType>\n" +
                "\t\t\t\t\t\t\t\t\t<HMDAEthnicityType>NotHispanicOrLatino</HMDAEthnicityType>\n" +
                "\t\t\t\t\t\t\t\t</GOVERNMENT_MONITORING_DETAIL>\n" +
                "\t\t\t\t\t\t\t\t<HMDA_RACES>\n" +
                "\t\t\t\t\t\t\t\t\t<HMDA_RACE>\n" +
                "\t\t\t\t\t\t\t\t\t\t<HMDARaceType>White</HMDARaceType>\n" +
                "\t\t\t\t\t\t\t\t\t</HMDA_RACE>\n" +
                "\t\t\t\t\t\t\t\t</HMDA_RACES>\n" +
                "\t\t\t\t\t\t\t</GOVERNMENT_MONITORING>\n" +
                "\t\t\t\t\t\t</BORROWER>\n" +
                "\t\t\t\t\t\t<ROLE_DETAIL>\n" +
                "\t\t\t\t\t\t\t<PartyRoleType>Borrower</PartyRoleType>\n" +
                "\t\t\t\t\t\t</ROLE_DETAIL>\n" +
                "\t\t\t\t\t</ROLE>\n" +
                "\t\t\t\t</ROLES>\n" +
                "\t\t\t\t<TAXPAYER_IDENTIFIERS>\n" +
                "\t\t\t\t\t<TAXPAYER_IDENTIFIER>\n" +
                "\t\t\t\t\t\t<TaxpayerIdentifierType>SocialSecurityNumber</TaxpayerIdentifierType>\n" +
                "\t\t\t\t\t\t<TaxpayerIdentifierValue>222222222</TaxpayerIdentifierValue>\n" +
                "\t\t\t\t\t</TAXPAYER_IDENTIFIER>\n" +
                "\t\t\t\t</TAXPAYER_IDENTIFIERS>\n" +
                "\t\t\t</PARTY>\n" +
                "\t\t\t<PARTY>\n" +
                "\t\t\t\t<ROLES>\n" +
                "\t\t\t\t\t<ROLE>\n" +
                "\t\t\t\t\t\t<LICENSES>\n" +
                "\t\t\t\t\t\t\t<LICENSE>\n" +
                "\t\t\t\t\t\t\t\t<LICENSE_DETAIL>\n" +
                "\t\t\t\t\t\t\t\t\t<LicenseIdentifier>nmls1</LicenseIdentifier>\n" +
                "\t\t\t\t\t\t\t\t</LICENSE_DETAIL>\n" +
                "\t\t\t\t\t\t\t</LICENSE>\n" +
                "\t\t\t\t\t\t</LICENSES>\n" +
                "\t\t\t\t\t\t<ROLE_DETAIL>\n" +
                "\t\t\t\t\t\t\t<PartyRoleType>ThirdPartyOriginator</PartyRoleType>\n" +
                "\t\t\t\t\t\t</ROLE_DETAIL>\n" +
                "\t\t\t\t\t</ROLE>\n" +
                "\t\t\t\t</ROLES>\n" +
                "\t\t\t</PARTY>\n" +
                "\t\t\t<PARTY>\n" +
                "\t\t\t\t<LEGAL_ENTITY>\n" +
                "\t\t\t\t\t<LEGAL_ENTITY_DETAIL>\n" +
                "\t\t\t\t\t\t<FullName>boom1</FullName>\n" +
                "\t\t\t\t\t</LEGAL_ENTITY_DETAIL>\n" +
                "\t\t\t\t</LEGAL_ENTITY>\n" +
                "\t\t\t\t<ROLES>\n" +
                "\t\t\t\t\t<ROLE>\n" +
                "\t\t\t\t\t\t<ROLE_DETAIL>\n" +
                "\t\t\t\t\t\t\t<PartyRoleType>SubmittingParty</PartyRoleType>\n" +
                "\t\t\t\t\t\t</ROLE_DETAIL>\n" +
                "\t\t\t\t\t</ROLE>\n" +
                "\t\t\t\t</ROLES>\n" +
                "\t\t\t</PARTY>\n" +
                "\t\t\t<PARTY>\n" +
                "\t\t\t\t<LEGAL_ENTITY>\n" +
                "\t\t\t\t\t<LEGAL_ENTITY_DETAIL>\n" +
                "\t\t\t\t\t\t<FullName>boom2</FullName>\n" +
                "\t\t\t\t\t</LEGAL_ENTITY_DETAIL>\n" +
                "\t\t\t\t</LEGAL_ENTITY>\n" +
                "\t\t\t\t<ROLES>\n" +
                "\t\t\t\t\t<ROLE>\n" +
                "\t\t\t\t\t\t<ROLE_DETAIL>\n" +
                "\t\t\t\t\t\t\t<PartyRoleType>Investor</PartyRoleType>\n" +
                "\t\t\t\t\t\t</ROLE_DETAIL>\n" +
                "\t\t\t\t\t</ROLE>\n" +
                "\t\t\t\t</ROLES>\n" +
                "\t\t\t</PARTY>\n" +
                "\t\t</PARTIES>\n" +
                "\t\t<SERVICES>\n" +
                "\t\t\t<SERVICE>\n" +
                "\t\t\t\t<MI>\n" +
                "\t\t\t\t\t<MI_APPLICATION_REQUEST>\n" +
                "\t\t\t\t\t\t<MI_APPLICATION>\n" +
                "\t\t\t\t\t\t\t<MIApplicationType>Delegated</MIApplicationType>\n" +
                "\t\t\t\t\t\t\t<!--\n" +
                "                <MICertificateIdentifier>RDNTEST</MICertificateIdentifier>\n" +
                "-->\n" +
                "\t\t\t\t\t\t\t<EXTENSION>\n" +
                "\t\t\t\t\t\t\t\t<OTHER>\n" +
                "\t\t\t\t\t\t\t\t\t<MIApplicationInputOptionType>FullMIApplication</MIApplicationInputOptionType>\n" +
                "\t\t\t\t\t\t\t\t</OTHER>\n" +
                "\t\t\t\t\t\t\t</EXTENSION>\n" +
                "\t\t\t\t\t\t\t<MILenderIdentifier>55</MILenderIdentifier>\n" +
                "\t\t\t\t\t\t</MI_APPLICATION>\n" +
                "\t\t\t\t\t\t<MI_APPLICATION_REQUEST_DETAIL>\n" +
                "\t\t\t\t\t\t\t<MIApplicationRequestType>Other</MIApplicationRequestType>\n" +
                "\t\t\t\t\t\t\t<MIApplicationRequestTypeOtherDescription>UpdateOnly</MIApplicationRequestTypeOtherDescription>\n" +
                "\t\t\t\t\t\t</MI_APPLICATION_REQUEST_DETAIL>\n" +
                "\t\t\t\t\t\t<MI_PRODUCTS>\n" +
                "\t\t\t\t\t\t\t<MI_PRODUCT>\n" +
                "\t\t\t\t\t\t\t\t<MICoveragePercent>30</MICoveragePercent>\n" +
                "\t\t\t\t\t\t\t\t<MIDurationType>Annual</MIDurationType>\n" +
                "\t\t\t\t\t\t\t\t<MIInitialPremiumAtClosingType>Deferred</MIInitialPremiumAtClosingType>\n" +
                "\t\t\t\t\t\t\t\t<MIPremiumCalculationType>Constant</MIPremiumCalculationType>\n" +
                "\t\t\t\t\t\t\t\t<MIPremiumRefundableType>Refundable</MIPremiumRefundableType>\n" +
                "\t\t\t\t\t\t\t\t<MIPremiumSourceType>Borrower</MIPremiumSourceType>\n" +
                "\t\t\t\t\t\t\t\t<MIPremiumUpfrontPercent>0.5</MIPremiumUpfrontPercent>\n" +
                "\t\t\t\t\t\t\t\t<EXTENSION>\n" +
                "\t\t\t\t\t\t\t\t\t<OTHER>\n" +
                "\t\t\t\t\t\t\t\t\t\t<GSECoveragePercentageIndicator>true</GSECoveragePercentageIndicator>\n" +
                "\t\t\t\t\t\t\t\t\t</OTHER>\n" +
                "\t\t\t\t\t\t\t\t</EXTENSION>\n" +
                "\t\t\t\t\t\t\t</MI_PRODUCT>\n" +
                "\t\t\t\t\t\t</MI_PRODUCTS>\n" +
                "\t\t\t\t\t</MI_APPLICATION_REQUEST>\n" +
                "\t\t\t\t</MI>\n" +
                "\t\t\t\t<CREDIT/>\n" +
                "\t\t\t</SERVICE>\n" +
                "\t\t</SERVICES>\n" +
                "\t\t<NOTES>\n" +
                "\t\t\t<NOTE>\n" +
                "\t\t\t\t<NoteIdentifier>10000001</NoteIdentifier>\n" +
                "\t\t\t\t<NoteDatetime>2014-04-24T14:17:15.42-04:00</NoteDatetime>\n" +
                "\t\t\t\t<NoteTypeDescription>notetype</NoteTypeDescription>\n" +
                "\t\t\t\t<NoteText>this is the first note</NoteText>\n" +
                "\t\t\t\t<NoteUserName>username</NoteUserName>\n" +
                "\t\t\t\t<NotePriorityIndicator>false</NotePriorityIndicator>\n" +
                "\t\t\t</NOTE>\n" +
                "\t\t\t<NOTE>\n" +
                "\t\t\t\t<NoteIdentifier>10000002</NoteIdentifier>\n" +
                "\t\t\t\t<NoteDatetime>2014-04-24T14:17:15.42-04:00</NoteDatetime>\n" +
                "\t\t\t\t<NoteTypeDescription>notetype</NoteTypeDescription>\n" +
                "\t\t\t\t<NoteText>this is the second note</NoteText>\n" +
                "\t\t\t\t<NoteUserName>username</NoteUserName>\n" +
                "\t\t\t\t<NotePriorityIndicator>false</NotePriorityIndicator>\n" +
                "\t\t\t</NOTE>\n" +
                "\t\t</NOTES>\n" +
                "\t</MORTGAGEINS_XCM>\n" +
                "</MESSAGE>\n";
    }


}
