#!/bin/bash

## Lets a data-access user create default Countries, Cities and States in the database
## --user/-u = user:password - FD_USER (data access account) that can write data
## --jar/-j if you're not using the standard fd-client JAR file, you can override it here

# fdcountries -u demo:123
## You can also run this as a docker or docker-compose command

# docker run flockdata/fd-client fdcountries -u=demo:123 --org.fd.engine.url=http://fd-engine:8080
FD_SCRIPT=$( cd "$( dirname "$0" )" && pwd )""
FD_ARGS="import"

source $FD_SCRIPT/fdutils
setBaseDir
readArgs

if [ -z "$FD_JAR" ]; then
    FD_JAR="$FD_BASE/fd-client.jar"
fi

if [ -n "$USER" ]; then
    FD_ARGS="$FD_ARGS --auth.user=$USER"
fi

if [ -n "$APIKEY" ]; then
    FD_ARGS="$FD_ARGS --org.fd.client.apikey=$APIKEY "
fi
DIR="$( cd "$( dirname "$0" )" && pwd )"

cd $FD_BASE
java  "-Dfile.encoding=UTF8" \
    -jar $FD_JAR \
    $FD_ARGS \
    "-Dlogging.config=$FD_BASE/conf/log4j2.yml" \
    --fd.client.import="/fd-cow.txt,/countries.json;/states.csv,/states.json"

