#!/bin/bash

## Lets a data-access user import data
## --user/-u = user:password - FD_USER (data access account) that can write data
## --jar/-j if you're not using the standard fd-client JAR file, you can override it here
## --fd.client.import="path/to/data.txt,path/to/profile.json"

# fdimport -u demo:123 --fd.client.import="path/to/data.txt,path/to/profile.json"
## You can also run this as a docker or docker-compose command

# docker run flockdata/fd-client fdimport -u=demo:123 --org.fd.engine.url=http://fd-engine:8080 --fd.client.import="path/to/data.txt,path/to/profile.json"

FD_SCRIPT=$( cd "$( dirname "$0" )" && pwd )""
FD_ARGS="ping"

source $FD_SCRIPT/fdutils
setBaseDir
readArgs

if [ -z "$FD_JAR" ]; then
    FD_JAR="$FD_BASE/fd-client.jar"
fi

if [ -n "$USER" ]; then
    FD_ARGS="$FD_ARGS --auth.user=$USER"
fi

if [ -n "$SERVICE" ]; then
    FD_ARGS="$FD_ARGS --org.fd.engine.api=$SERVICE"
fi

if [ -n "$APIKEY" ]; then
    FD_ARGS="$FD_ARGS --org.fd.client.apikey=$APIKEY "
fi
DIR="$( cd "$( dirname "$0" )" && pwd )"

cd $FD_BASE
java  "-Dfile.encoding=UTF8" \
    -jar $FD_JAR \
    $FD_ARGS \
    "-Dlogging.config=$FD_BASE/conf/log4j2.yml"

