#!/usr/bin/env bash

## Allows an authorised user to register a data access account in FlockData
## --user/-u = user:password - FD_ADMIN user authorised to perform this activity
## --login/-l = login account to grant data access to (should == users login name)
## --name/-n optional name to use

# fdregister -u=demo:123 -l=demo

# docker run flockdata/fd-client fdregister -u=demo:123 -l=demo --org.fd.engine.url=http://fd-engine:8080

FD_SCRIPT=$( cd "$( dirname "$0" )" && pwd )""
FD_ARGS="register "

source $FD_SCRIPT/fdutils
setBaseDir
readArgs

if [ -z "$FD_JAR" ]; then
    FD_JAR="$FD_BASE/fd-client.jar"
fi

if [ -n "$USER" ]; then
    FD_ARGS="$FD_ARGS --auth.user=$USER"
fi

if [ -n "$COMPANY" ]; then
    FD_ARGS="$FD_ARGS --org.fd.client.default.company=$COMPANY"
fi

if [ -n "$LOGIN" ]; then
    FD_ARGS="$FD_ARGS --register.login=$LOGIN"
fi

if [ -n "$APIKEY" ]; then
    FD_ARGS="$FD_ARGS --org.fd.client.apikey=$APIKEY "
fi

cd $FD_BASE

java  "-Dfile.encoding=UTF8" \
    -jar $FD_JAR \
    $FD_ARGS \
    "-Dlogging.config=$FD_BASE/conf/log4j2.yml"