#!/usr/bin/env bash

function setBaseDir() {
    if [ -z "$FD_BASE" ]; then
        FD_BASE=$( cd "$( dirname "$0" )" && pwd )""
    fi
}

function readArgs() {

    for i in ${BASH_ARGV[*]}
    do
    case $i in
        -u=*|--user=*)
        USER="${i#*=}" ;;

# Auth credentials to use -l=user:password
        -l=*|--login=*)
        LOGIN="${i#*=}" ;;

# Auth credentials to use -l=user:password
        -s=*|--service=*)
        SERVICE="${i#*=}" ;;

# Determine which Jar to execute
        -j=*|--jar=*)
        FD_JAR="${i#*=}" ;;

# Company the login belongs to
        -c=*|--company=*)
        COMPANY="${i#*=}" ;;

# Optional API key which bybasses the need to provide login
        -key=*|--apikey=*)
        APIKEY="${i#*=}" ;;

        *)
        # Add the remainder of the callers args
        FD_ARGS="$FD_ARGS ${i#*=}" ;;
    esac
    done
}